CREATE TABLE [dbo].[FHIR_TEI_ErrorMensajeSalidaInterconsulta] (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID () CONSTRAINT PK_FHIR_TEI_ERRORMENSAJESALIDAINTERCONSULTA PRIMARY KEY,

    IdMensajeSalidaInterconsulta UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT FK_FHIR_TEI_ERRORMENSAJESALIDAINTERCONSULTA_MENSAJESALIDAINTERCONSULTA FOREIGN KEY REFERENCES [dbo].[FHIR_TEI_MensajeSalidaInterconsulta] (Id),

    ErrorJSON VARCHAR(MAX) NOT NULL,

    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
)