CREATE TABLE [dbo].[FIHR_TEI_EventoInterconsulta] (
    IdInterconsulta BIGINT NOT NULL,
    IdTipoEvento TINYINT NOT NULL,

    CONSTRAINT PK_FIHR_TEI_EVENTOINTERCONSULTA PRIMARY KEY (IdInterconsulta, IdTipoEvento),
    CONSTRAINT FK_FIHR_TEI_EVENTOINTERCONSULTA_INTERCONSULTA FOREIGN KEY (IdInterconsulta) REFERENCES [dbo].[ListaEspera_Interconsulta] (Id),
    CONSTRAINT FK_FIHR_TEI_EVENTOINTERCONSULTA_TIPOEVENTOINTERCONSULTA FOREIGN KEY (IdTipoEvento) REFERENCES [dbo].[FHIR_TEI_TAB_TipoEventoInterconsulta] (Id)
    
)