IF (OBJECT_ID('dbo.FK_DOMICILIO_PACIENTE', 'F') IS NOT NULL) ALTER TABLE [dbo].[DomicilioPaciente] DROP CONSTRAINT FK_DOMICILIO_PACIENTE
IF (OBJECT_ID('dbo.FK_DOMICILIO_USO', 'F') IS NOT NULL) ALTER TABLE [dbo].[DomicilioPaciente] DROP CONSTRAINT FK_DOMICILIO_USO
IF (OBJECT_ID('dbo.FK_DOMICILIO_COMUNA', 'F') IS NOT NULL) ALTER TABLE [dbo].[DomicilioPaciente] DROP CONSTRAINT FK_DOMICILIO_COMUNA
IF (OBJECT_ID('dbo.FK_DOMICILIO_TIPOVIA', 'F') IS NOT NULL) ALTER TABLE [dbo].[DomicilioPaciente] DROP CONSTRAINT FK_DOMICILIO_TIPOVIA
IF (OBJECT_ID('dbo.FK_DOMICILIO_CREATEDBY', 'F') IS NOT NULL) ALTER TABLE [dbo].[DomicilioPaciente] DROP CONSTRAINT FK_DOMICILIO_CREATEDBY
IF (OBJECT_ID('dbo.FK_DOMICILIO_DELETEDBY', 'F') IS NOT NULL) ALTER TABLE [dbo].[DomicilioPaciente] DROP CONSTRAINT FK_DOMICILIO_DELETEDBY

IF (OBJECT_ID('dbo.FK_IDENTIFICADORPACIENTE_PACIENTE', 'F') IS NOT NULL) ALTER TABLE [dbo].[IdentificadorPaciente] DROP CONSTRAINT FK_IDENTIFICADORPACIENTE_PACIENTE
IF (OBJECT_ID('dbo.FK_IDENTIFICADORPACIENTE_TIPO', 'F') IS NOT NULL) ALTER TABLE [dbo].[IdentificadorPaciente] DROP CONSTRAINT FK_IDENTIFICADORPACIENTE_TIPO
IF (OBJECT_ID('dbo.FK_IDENTIFICADORPACIENTE_USO', 'F') IS NOT NULL) ALTER TABLE [dbo].[IdentificadorPaciente] DROP CONSTRAINT FK_IDENTIFICADORPACIENTE_USO
IF (OBJECT_ID('dbo.FK_IDENTIFICADORPACIENTE_PAIS', 'F') IS NOT NULL) ALTER TABLE [dbo].[IdentificadorPaciente] DROP CONSTRAINT FK_IDENTIFICADORPACIENTE_PAIS
IF (OBJECT_ID('dbo.FK_IDENTIFICADORPACIENTE_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[IdentificadorPaciente] DROP CONSTRAINT FK_IDENTIFICADORPACIENTE_USUARIO

IF (OBJECT_ID('dbo.FK_MEDIOCONTACTO_PACIENTE', 'F') IS NOT NULL) ALTER TABLE [dbo].[MedioContactoPaciente] DROP CONSTRAINT FK_MEDIOCONTACTO_PACIENTE
IF (OBJECT_ID('dbo.FK_MEDIOCONTACTO_TIPO', 'F') IS NOT NULL) ALTER TABLE [dbo].[MedioContactoPaciente] DROP CONSTRAINT FK_MEDIOCONTACTO_TIPO
IF (OBJECT_ID('dbo.FK_MEDIOCONTACTO_USO', 'F') IS NOT NULL) ALTER TABLE [dbo].[MedioContactoPaciente] DROP CONSTRAINT FK_MEDIOCONTACTO_USO
IF (OBJECT_ID('dbo.FK_MEDIOCONTACTO_CREATEDBY', 'F') IS NOT NULL) ALTER TABLE [dbo].[MedioContactoPaciente] DROP CONSTRAINT FK_MEDIOCONTACTO_CREATEDBY
IF (OBJECT_ID('dbo.FK_MEDIOCONTACTO_DELETEDBY', 'F') IS NOT NULL) ALTER TABLE [dbo].[MedioContactoPaciente] DROP CONSTRAINT FK_MEDIOCONTACTO_DELETEDBY

IF (OBJECT_ID('dbo.FK_PACIENTEFHIR_PACIENTE', 'F') IS NOT NULL) ALTER TABLE [dbo].[PacienteFHIR] DROP CONSTRAINT FK_PACIENTEFHIR_PACIENTE
IF (OBJECT_ID('dbo.FK_PACIENTEFHIR_GENEROADMINISTRATIVO', 'F') IS NOT NULL) ALTER TABLE [dbo].[PacienteFHIR] DROP CONSTRAINT FK_PACIENTEFHIR_GENEROADMINISTRATIVO

IF (OBJECT_ID('dbo.FK_PACIENTE_PERSONACONTACTO', 'F') IS NOT NULL) ALTER TABLE [dbo].[PersonaContactoPaciente] DROP CONSTRAINT FK_PACIENTE_PERSONACONTACTO
IF (OBJECT_ID('dbo.FK_PERSONACONTACTO_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[PersonaContactoPaciente] DROP CONSTRAINT FK_PERSONACONTACTO_USUARIO

IF (OBJECT_ID('dbo.FK_RELACIONPERSONACONTACTOPACIENTE', 'F') IS NOT NULL) ALTER TABLE [dbo].[RelacionPersonaContactoPaciente] DROP CONSTRAINT FK_RELACIONPERSONACONTACTOPACIENTE
IF (OBJECT_ID('dbo.FK_RELACIONPERSONACONTACTOPACIENTE_RELACION', 'F') IS NOT NULL) ALTER TABLE [dbo].[RelacionPersonaContactoPaciente] DROP CONSTRAINT FK_RELACIONPERSONACONTACTOPACIENTE_RELACION
IF (OBJECT_ID('dbo.FK_RELACIONPERSONACONTACTOPACIENTE_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[RelacionPersonaContactoPaciente] DROP CONSTRAINT FK_RELACIONPERSONACONTACTOPACIENTE_USUARIO

-- ********************************************************************

IF (OBJECT_ID('dbo.FK_DEIS_COMUNA_PROVINCIA', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_DEIS_Comuna] DROP CONSTRAINT FK_DEIS_COMUNA_PROVINCIA
IF (OBJECT_ID('dbo.FK_DEIS_COMUNA_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_DEIS_Comuna] DROP CONSTRAINT FK_DEIS_COMUNA_USUARIO
IF (OBJECT_ID('dbo.FK_DEIS_ESTADOCIVIL_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_DEIS_EstadoCivil] DROP CONSTRAINT FK_DEIS_ESTADOCIVIL_USUARIO
IF (OBJECT_ID('dbo.FK_DEIS_IDENTIDADGENERO_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_DEIS_IdentidadGenero] DROP CONSTRAINT FK_DEIS_IDENTIDADGENERO_USUARIO
IF (OBJECT_ID('dbo.FK_DEIS_PAIS_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_DEIS_Pais] DROP CONSTRAINT FK_DEIS_PAIS_USUARIO
IF (OBJECT_ID('dbo.FK_DEIS_PROVINCIA_REGION', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_DEIS_Provincia] DROP CONSTRAINT FK_DEIS_PROVINCIA_REGION
IF (OBJECT_ID('dbo.FK_DEIS_PROVINCIA_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_DEIS_Provincia] DROP CONSTRAINT FK_DEIS_PROVINCIA_USUARIO
IF (OBJECT_ID('dbo.FK_DEIS_PUEBLOORIGINARIO_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_DEIS_PuebloOriginario] DROP CONSTRAINT FK_DEIS_PUEBLOORIGINARIO_USUARIO
IF (OBJECT_ID('dbo.FK_DEIS_REGION_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_DEIS_Region] DROP CONSTRAINT FK_DEIS_REGION_USUARIO
IF (OBJECT_ID('dbo.FK_DEIS_RELIGION_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_DEIS_Religion] DROP CONSTRAINT FK_DEIS_RELIGION_USUARIO
IF (OBJECT_ID('dbo.FK_DEIS_SEXOBIOLOGICO_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_DEIS_SexoBiologico] DROP CONSTRAINT FK_DEIS_SEXOBIOLOGICO_USUARIO
IF (OBJECT_ID('dbo.FK_DEIS_TIPOVIA_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_DEIS_TipoVia] DROP CONSTRAINT FK_DEIS_TIPOVIA_USUARIO
IF (OBJECT_ID('dbo.FK_FHIR_RELACIONCONTACTOPACIENTE_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_FHIR_RelacionContactoPaciente] DROP CONSTRAINT FK_FHIR_RELACIONCONTACTOPACIENTE_USUARIO
IF (OBJECT_ID('dbo.FK_FHIR_TIPOIDENTIFICADORPERSONA_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_FHIR_TipoIdentificadorPersona] DROP CONSTRAINT FK_FHIR_TIPOIDENTIFICADORPERSONA_USUARIO
IF (OBJECT_ID('dbo.FK_FHIR_USODOMICILIOPERSONA_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_FHIR_UsoDomicilioPersona] DROP CONSTRAINT FK_FHIR_USODOMICILIOPERSONA_USUARIO
IF (OBJECT_ID('dbo.FK_FHIR_USOIDENTIFICADORPERSONA_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_FHIR_UsoIdentificadorPersona] DROP CONSTRAINT FK_FHIR_USOIDENTIFICADORPERSONA_USUARIO
IF (OBJECT_ID('dbo.FK_FHIR_USOMEDIOCONTACTO_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_FHIR_UsoMedioContacto] DROP CONSTRAINT FK_FHIR_USOMEDIOCONTACTO_USUARIO
IF (OBJECT_ID('dbo.FK_TIPOMEDIOCONTACTO_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_TipoMedioContacto] DROP CONSTRAINT FK_TIPOMEDIOCONTACTO_USUARIO

-- ****************************************************************

IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_SEXOBILOGICO', 'F') IS NOT NULL) ALTER TABLE [dbo].[PAC_Paciente] DROP CONSTRAINT FK_PAC_PACIENTE_SEXOBILOGICO
IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_IDENTIDADGENERO', 'F') IS NOT NULL) ALTER TABLE [dbo].[PAC_Paciente] DROP CONSTRAINT FK_PAC_PACIENTE_IDENTIDADGENERO
IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_NACIONALIDAD', 'F') IS NOT NULL) ALTER TABLE [dbo].[PAC_Paciente] DROP CONSTRAINT FK_PAC_PACIENTE_NACIONALIDAD
IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_PAISORIGEN', 'F') IS NOT NULL) ALTER TABLE [dbo].[PAC_Paciente] DROP CONSTRAINT FK_PAC_PACIENTE_PAISORIGEN
IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_ESTADOCIVIL', 'F') IS NOT NULL) ALTER TABLE [dbo].[PAC_Paciente] DROP CONSTRAINT FK_PAC_PACIENTE_ESTADOCIVIL
IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_PUEBLOORIGINARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[PAC_Paciente] DROP CONSTRAINT FK_PAC_PACIENTE_PUEBLOORIGINARIO
IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_RELIGION', 'F') IS NOT NULL) ALTER TABLE [dbo].[PAC_Paciente] DROP CONSTRAINT FK_PAC_PACIENTE_RELIGION

-- ***************************************************************



IF (OBJECT_ID('dbo.FK_MEDIOCONTACTOPRESTADOR_PRESTADOR', 'F') IS NOT NULL) ALTER TABLE [dbo].[MedioContactoPrestador] DROP CONSTRAINT FK_MEDIOCONTACTOPRESTADOR_PRESTADOR
IF (OBJECT_ID('dbo.FK_MEDIOCONTACTOPRESTADOR_TIPOMEDIOCONTACTO', 'F') IS NOT NULL) ALTER TABLE [dbo].[MedioContactoPrestador] DROP CONSTRAINT FK_MEDIOCONTACTOPRESTADOR_TIPOMEDIOCONTACTO
IF (OBJECT_ID('dbo.FK_MEDIOCONTACTOPRESTADOR_CREATEDBY', 'F') IS NOT NULL) ALTER TABLE [dbo].[MedioContactoPrestador] DROP CONSTRAINT FK_MEDIOCONTACTOPRESTADOR_CREATEDBY
IF (OBJECT_ID('dbo.FK_MEDIOCONTACTOPRESTADOR_DELETEDBY', 'F') IS NOT NULL) ALTER TABLE [dbo].[MedioContactoPrestador] DROP CONSTRAINT FK_MEDIOCONTACTOPRESTADOR_DELETEDBY

IF (OBJECT_ID('dbo.FK_DOMICILIOPRESTADOR_PRESTADOR', 'F') IS NOT NULL) ALTER TABLE [dbo].[DomicilioPrestador] DROP CONSTRAINT FK_DOMICILIOPRESTADOR_PRESTADOR
IF (OBJECT_ID('dbo.FK_DOMICILIOPRESTADOR_CREATEDBY', 'F') IS NOT NULL) ALTER TABLE [dbo].[DomicilioPrestador] DROP CONSTRAINT FK_DOMICILIOPRESTADOR_CREATEDBY
IF (OBJECT_ID('dbo.FK_DOMICILIOPRESTADOR_DELETEDBY', 'F') IS NOT NULL) ALTER TABLE [dbo].[DomicilioPrestador] DROP CONSTRAINT FK_DOMICILIOPRESTADOR_DELETEDBY
IF (OBJECT_ID('dbo.FK_PRESTADOREFHIR_PRESTADOR', 'F') IS NOT NULL) ALTER TABLE [dbo].[PrestadorFHIR] DROP CONSTRAINT FK_PRESTADOREFHIR_PRESTADOR
IF (OBJECT_ID('dbo.FK_PRESTADOREFHIR_GENEROADMINISTRATIVO', 'F') IS NOT NULL) ALTER TABLE [dbo].[PrestadorFHIR] DROP CONSTRAINT FK_PRESTADOREFHIR_GENEROADMINISTRATIVO
IF (OBJECT_ID('dbo.FK_TITULOPROFESIONALPRESTADOR_PRESTADOR', 'F') IS NOT NULL) ALTER TABLE [dbo].[TituloProfesionalPrestador] DROP CONSTRAINT FK_TITULOPROFESIONALPRESTADOR_PRESTADOR
IF (OBJECT_ID('dbo.FK_TITULOPROFESIONALPRESTADOR_TITULOPROFESIONAL', 'F') IS NOT NULL) ALTER TABLE [dbo].[TituloProfesionalPrestador] DROP CONSTRAINT FK_TITULOPROFESIONALPRESTADOR_TITULOPROFESIONAL
IF (OBJECT_ID('dbo.FK_TITULOPROFESIONALPRESTADOR_CREATEDBY', 'F') IS NOT NULL) ALTER TABLE [dbo].[TituloProfesionalPrestador] DROP CONSTRAINT FK_TITULOPROFESIONALPRESTADOR_CREATEDBY
IF (OBJECT_ID('dbo.FK_TITULOPROFESIONALPRESTADOR_DELETEDBY', 'F') IS NOT NULL) ALTER TABLE [dbo].[TituloProfesionalPrestador] DROP CONSTRAINT FK_TITULOPROFESIONALPRESTADOR_DELETEDBY

IF (OBJECT_ID('dbo.FK_DEIS_ESPECIALIDADMEDICA_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[TAB_DEIS_EspecialidadMedica] DROP CONSTRAINT FK_DEIS_ESPECIALIDADMEDICA_USUARIO


IF (OBJECT_ID('dbo.FK_ESPECIALIDADMEDICAPRESTADOR_PRESTADOR', 'F') IS NOT NULL) ALTER TABLE EspecialidadMedicaPrestador DROP CONSTRAINT FK_ESPECIALIDADMEDICAPRESTADOR_PRESTADOR
IF (OBJECT_ID('dbo.FK_ESPECIALIDADMEDICAPRESTADOR_ESPECIALIDAD', 'F') IS NOT NULL) ALTER TABLE EspecialidadMedicaPrestador DROP CONSTRAINT FK_ESPECIALIDADMEDICAPRESTADOR_ESPECIALIDAD
IF (OBJECT_ID('dbo.FK_ESPECIALIDADMEDICAPRESTADOR_CREATEDBY', 'F') IS NOT NULL) ALTER TABLE EspecialidadMedicaPrestador DROP CONSTRAINT FK_ESPECIALIDADMEDICAPRESTADOR_CREATEDBY
IF (OBJECT_ID('dbo.FK_ESPECIALIDADMEDICAPRESTADOR_DELETEDBY', 'F') IS NOT NULL) ALTER TABLE EspecialidadMedicaPrestador DROP CONSTRAINT FK_ESPECIALIDADMEDICAPRESTADOR_DELETEDBY

IF (OBJECT_ID('dbo.FK_SOLICITUDINTERCONSULTA_PACIENTE', 'F') IS NOT NULL) ALTER TABLE SolicitudInterconsulta DROP CONSTRAINT FK_SOLICITUDINTERCONSULTA_PACIENTE
IF (OBJECT_ID('dbo.FK_SOLICITUDINTERCONSULTA_ESPECIALIDAD', 'F') IS NOT NULL) ALTER TABLE SolicitudInterconsulta DROP CONSTRAINT FK_SOLICITUDINTERCONSULTA_ESPECIALIDAD
IF (OBJECT_ID('dbo.FK_SOLICITUDINTERCONSULTA_SUBESPECIALIDAD', 'F') IS NOT NULL) ALTER TABLE SolicitudInterconsulta DROP CONSTRAINT FK_SOLICITUDINTERCONSULTA_SUBESPECIALIDAD
IF (OBJECT_ID('dbo.FK_SOLICITUDINTERCONSULTA_MOTIVOCIERREINTERCONSULTA', 'F') IS NOT NULL) ALTER TABLE SolicitudInterconsulta DROP CONSTRAINT FK_SOLICITUDINTERCONSULTA_MOTIVOCIERREINTERCONSULTA

IF (OBJECT_ID('dbo.FK_FHIR_BUNDLEINICIARENRIQUECIDO_SOLICITUDINTERCONSULTA', 'F') IS NOT NULL) ALTER TABLE FHIR_BundleIniciarEnriquecido DROP CONSTRAINT FK_FHIR_BUNDLEINICIARENRIQUECIDO_SOLICITUDINTERCONSULTA

IF (OBJECT_ID('dbo.FK_FHIR_MOTIVOCIERREINTERCONSULTA_USUARIO', 'F') IS NOT NULL) ALTER TABLE TAB_FHIR_MotivoCierreInterconsulta DROP CONSTRAINT FK_FHIR_MOTIVOCIERREINTERCONSULTA_USUARIO


-- ***


IF (OBJECT_ID('dbo.FK_LE_ESTADOINTERCONSULTA_ESTADO', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_EstadoInterconsulta] DROP CONSTRAINT [FK_LE_ESTADOINTERCONSULTA_ESTADO];
IF (OBJECT_ID('dbo.FK_LE_ESTADOINTERCONSULTA_INTERCONSULTA', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_EstadoInterconsulta] DROP CONSTRAINT [FK_LE_ESTADOINTERCONSULTA_INTERCONSULTA];
IF (OBJECT_ID('dbo.FK_LE_ESTADOINTERCONSULTA_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_EstadoInterconsulta] DROP CONSTRAINT [FK_LE_ESTADOINTERCONSULTA_USUARIO];


IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_PACIENTE', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_PACIENTE;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_SISTEMAORIGEN', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_SISTEMAORIGEN;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_ESPECIALIDADORIGEN', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_ESPECIALIDADORIGEN;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_POLICLINICOORIGEN', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_POLICLINICOORIGEN;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_NOMINA', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_NOMINA;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_ESTABLECIMIENTOORIGEN', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_ESTABLECIMIENTOORIGEN;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_ESTABLEDESTINO', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_ESTABLEDESTINO;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_ESPECIALIDADDESTINO', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_ESPECIALIDADDESTINO;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_DIAGNOSTICO', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_DIAGNOSTICO;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_ESTADODIAGNOSTICO', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_ESTADODIAGNOSTICO;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_MOTIVODERIVACION', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_MOTIVODERIVACION;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_TIPOPRESTACION', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_TIPOPRESTACION;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_PRIORIDAD', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_PRIORIDAD;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_USUARIO_PRIORIZADOR', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_USUARIO_PRIORIZADOR;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_CAUSASALIDA', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_CAUSASALIDA;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_MODALIDADATENCION', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_MODALIDADATENCION;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_USUARIO', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_USUARIO;
IF (OBJECT_ID('dbo.K_LE_INTERCONSULTA_PROFESIONALORIGEN', 'F') IS NOT NULL) ALTER TABLE [dbo].[ListaEspera_Interconsulta] DROP CONSTRAINT FK_LE_INTERCONSULTA_PROFESIONALORIGEN;
