ALTER TABLE [dbo].[DomicilioPaciente]
ADD
    -- CONSTRAINT PK_DOMICILIO PRIMARY KEY (Id),
    CONSTRAINT FK_DOMICILIO_PACIENTE FOREIGN KEY (NumeroPaciente) REFERENCES [dbo].[PAC_Paciente](PAC_PAC_Numero),
    CONSTRAINT FK_DOMICILIO_USO FOREIGN KEY (IdUso) REFERENCES [dbo].[TAB_FHIR_UsoDomicilioPersona](Id),
    CONSTRAINT FK_DOMICILIO_COMUNA FOREIGN KEY (IdComuna) REFERENCES [dbo].[TAB_DEIS_Comuna](Id),
    CONSTRAINT FK_DOMICILIO_TIPOVIA FOREIGN KEY (IdTipoVia) REFERENCES [dbo].[TAB_DEIS_TipoVia](Id),
    CONSTRAINT FK_DOMICILIO_CREATEDBY FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]),
    CONSTRAINT FK_DOMICILIO_DELETEDBY FOREIGN KEY (DeletedBy)REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);

ALTER TABLE [dbo].[IdentificadorPaciente]
ADD
    -- CONSTRAINT PK_IDENTIFICADOR PRIMARY KEY (Id),
    CONSTRAINT FK_IDENTIFICADORPACIENTE_PACIENTE FOREIGN KEY (NumeroPaciente) REFERENCES [dbo].[PAC_Paciente](PAC_PAC_Numero),
    CONSTRAINT FK_IDENTIFICADORPACIENTE_TIPO FOREIGN KEY (IdTipo) REFERENCES [dbo].[TAB_FHIR_TipoIdentificadorPersona](Id),
    CONSTRAINT FK_IDENTIFICADORPACIENTE_USO FOREIGN KEY (IdUso) REFERENCES [dbo].[TAB_FHIR_UsoIdentificadorPersona](Id),
    CONSTRAINT FK_IDENTIFICADORPACIENTE_PAIS FOREIGN KEY (IdPaisEmisorDocumento) REFERENCES [dbo].[TAB_DEIS_Pais](Id),
    CONSTRAINT FK_IDENTIFICADORPACIENTE_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);


ALTER TABLE [dbo].[MedioContactoPaciente]
ADD
    -- CONSTRAINT PK_MEDIOCONTACTO PRIMARY KEY (Id),
    CONSTRAINT FK_MEDIOCONTACTO_PACIENTE FOREIGN KEY (NumeroPaciente) REFERENCES [dbo].[PAC_Paciente](PAC_PAC_Numero),
    CONSTRAINT FK_MEDIOCONTACTO_TIPO FOREIGN KEY (IdTipo) REFERENCES [dbo].[TAB_TipoMedioContacto](Id),
    CONSTRAINT FK_MEDIOCONTACTO_USO FOREIGN KEY (CodigoUso) REFERENCES [dbo].[TAB_FHIR_UsoMedioContacto](Codigo),
    CONSTRAINT FK_MEDIOCONTACTO_CREATEDBY FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]),
    CONSTRAINT FK_MEDIOCONTACTO_DELETEDBY FOREIGN KEY (DeletedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);

ALTER TABLE [dbo].[PacienteFHIR]
ADD
    CONSTRAINT FK_PACIENTEFHIR_PACIENTE FOREIGN KEY (NumeroPaciente) REFERENCES [dbo].[PAC_Paciente]([PAC_PAC_Numero]),
    CONSTRAINT FK_PACIENTEFHIR_GENEROADMINISTRATIVO FOREIGN KEY (FHIR_IdGeneroAdministrativo) REFERENCES [dbo].[TAB_DEIS_SexoBiologico]([Id]);

ALTER TABLE [dbo].[PersonaContactoPaciente]
ADD
    -- CONSTRAINT PK_PERSONACONTACTO PRIMARY KEY (Id),
    CONSTRAINT FK_PACIENTE_PERSONACONTACTO FOREIGN KEY (NumeroPaciente) REFERENCES [dbo].[PAC_Paciente](PAC_PAC_Numero),
    CONSTRAINT FK_PERSONACONTACTO_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);


ALTER TABLE [dbo].[RelacionPersonaContactoPaciente]
ADD
    -- CONSTRAINT PK_RELACIONPERSONACONTACTOPACIENTE PRIMARY KEY (IdPersonaContacto, CodigoRelacion),
    CONSTRAINT FK_RELACIONPERSONACONTACTOPACIENTE FOREIGN KEY (IdPersonaContacto) REFERENCES PersonaContactoPaciente(Id),
    CONSTRAINT FK_RELACIONPERSONACONTACTOPACIENTE_RELACION FOREIGN KEY (CodigoRelacion) REFERENCES TAB_FHIR_RelacionContactoPaciente(Codigo),
    CONSTRAINT FK_RELACIONPERSONACONTACTOPACIENTE_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);

-- ********************************************************************
ALTER TABLE [dbo].[TAB_DEIS_Comuna]
ADD
    -- CONSTRAINT PK_DEIS_COMUNA PRIMARY KEY (Id),
    CONSTRAINT FK_DEIS_COMUNA_PROVINCIA FOREIGN KEY (IdProvincia) REFERENCES [dbo].[TAB_DEIS_Provincia]([Id]),
    CONSTRAINT FK_DEIS_COMUNA_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);


ALTER TABLE [dbo].[TAB_DEIS_EstadoCivil]
ADD
    -- CONSTRAINT PK_DEIS_ESTADOCIVIL PRIMARY KEY (Id),
    CONSTRAINT FK_DEIS_ESTADOCIVIL_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);


ALTER TABLE [dbo].[TAB_DEIS_IdentidadGenero]
ADD
    -- CONSTRAINT PK_DEIS_IDENTIDADGENERO PRIMARY KEY (Id),
    CONSTRAINT FK_DEIS_IDENTIDADGENERO_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);

ALTER TABLE [dbo].[TAB_DEIS_Pais]
ADD
    -- -- CONSTRAINT PK_DEIS_PAIS PRIMARY KEY (Id),
    CONSTRAINT FK_DEIS_PAIS_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);


ALTER TABLE [dbo].[TAB_DEIS_Provincia]
ADD
    -- -- CONSTRAINT PK_DEIS_PROVINCIA PRIMARY KEY,
    CONSTRAINT FK_DEIS_PROVINCIA_REGION FOREIGN KEY (IdRegion) REFERENCES [dbo].[TAB_DEIS_Region]([Id]),
    CONSTRAINT FK_DEIS_PROVINCIA_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);

ALTER TABLE [dbo].[TAB_DEIS_PuebloOriginario]
ADD
    -- CONSTRAINT PK_DEIS_PUEBLOORIGINARIO PRIMARY KEY (Id),
    CONSTRAINT FK_DEIS_PUEBLOORIGINARIO_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);


ALTER TABLE [dbo].[TAB_DEIS_Region]
ADD
    -- CONSTRAINT PK_DEIS_REGION PRIMARY KEY (Id),
    CONSTRAINT FK_DEIS_REGION_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);


ALTER TABLE [dbo].[TAB_DEIS_Religion]
ADD
    -- CONSTRAINT PK_DEIS_RELIGION PRIMARY KEY (Id),
    CONSTRAINT FK_DEIS_RELIGION_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);


ALTER TABLE [dbo].[TAB_DEIS_SexoBiologico]
ADD
    -- CONSTRAINT PK_DEIS_SEXOBIOLOGICO PRIMARY KEY (Id),
    CONSTRAINT FK_DEIS_SEXOBIOLOGICO_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);

ALTER TABLE [dbo].[TAB_DEIS_TipoVia]
ADD
    -- CONSTRAINT PK_DEIS_TIPOVIA PRIMARY KEY(Id),
    CONSTRAINT FK_DEIS_TIPOVIA_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);

ALTER TABLE [dbo].[TAB_FHIR_RelacionContactoPaciente]
ADD
    -- CONSTRAINT PK_FHIR_RELACIONCONTACTOPACIENTE PRIMARY KEY (Id),
    CONSTRAINT FK_FHIR_RELACIONCONTACTOPACIENTE_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);


ALTER TABLE TAB_FHIR_TipoIdentificadorPersona
ADD
    -- CONSTRAINT PK_FHIR_TIPOIDENTIFICADORPERSONA PRIMARY KEY (Id),
    CONSTRAINT FK_FHIR_TIPOIDENTIFICADORPERSONA_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);


ALTER TABLE [dbo].[TAB_FHIR_UsoDomicilioPersona]
ADD
    -- CONSTRAINT PK_FHIR_USODOMICILIOPERSONA PRIMARY KEY (Id),
    CONSTRAINT FK_FHIR_USODOMICILIOPERSONA_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);


ALTER TABLE [dbo].[TAB_FHIR_UsoIdentificadorPersona]
ADD
    -- CONSTRAINT PK_FHIR_USOIDENTIFICADORPERSONA PRIMARY KEY (Id),
    CONSTRAINT FK_FHIR_USOIDENTIFICADORPERSONA_USUARIO FOREIGN KEY(CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);

ALTER TABLE [dbo].[TAB_FHIR_UsoMedioContacto]
ADD
    -- CONSTRAINT PK_FHIR_USOMEDIOCONTACTO PRIMARY KEY (Id),
    CONSTRAINT FK_FHIR_USOMEDIOCONTACTO_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);

ALTER TABLE [dbo].[TAB_TipoMedioContacto]
ADD
    -- CONSTRAINT PK_TIPOMEDIOCONTACTO PRIMARY KEY (Id),
    CONSTRAINT FK_TIPOMEDIOCONTACTO_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);



-- ************************************************************************************************

ALTER TABLE [dbo].[PAC_Paciente]
ADD
    CONSTRAINT FK_PAC_PACIENTE_SEXOBILOGICO FOREIGN KEY (IdSexoBiologico) REFERENCES [dbo].[TAB_DEIS_SexoBiologico]([Id]),
    CONSTRAINT FK_PAC_PACIENTE_IDENTIDADGENERO FOREIGN KEY (IdIdentidadGenero) REFERENCES [dbo].[TAB_DEIS_IdentidadGenero]([Id]),
    CONSTRAINT FK_PAC_PACIENTE_NACIONALIDAD FOREIGN KEY (IdNacionalidad) REFERENCES [dbo].[TAB_DEIS_Pais]([Id]),
    CONSTRAINT FK_PAC_PACIENTE_PAISORIGEN FOREIGN KEY (IdPaisOrigen) REFERENCES [dbo].[TAB_DEIS_Pais]([Id]),
    CONSTRAINT FK_PAC_PACIENTE_ESTADOCIVIL FOREIGN KEY (IdEstadoCivil) REFERENCES [dbo].[TAB_DEIS_EstadoCivil]([Id]),
    CONSTRAINT FK_PAC_PACIENTE_PUEBLOORIGINARIO FOREIGN KEY (IdPuebloOriginario) REFERENCES [dbo].[TAB_DEIS_PuebloOriginario]([Id]),
    CONSTRAINT FK_PAC_PACIENTE_RELIGION FOREIGN KEY (IdReligion) REFERENCES [dbo].[TAB_DEIS_Religion]([Id]);

-- ***********************************************************************************************

ALTER TABLE [dbo].[MedioContactoPrestador]
ADD
    CONSTRAINT FK_MEDIOCONTACTOPRESTADOR_PRESTADOR FOREIGN KEY (IdPrestador) REFERENCES [dbo].[SER_Profesiona]([Id]),
    CONSTRAINT FK_MEDIOCONTACTOPRESTADOR_TIPOMEDIOCONTACTO FOREIGN KEY (IdTipo) REFERENCES [dbo].[TAB_TipoMedioContacto]([Id]),
    CONSTRAINT FK_MEDIOCONTACTOPRESTADOR_CREATEDBY FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]),
    CONSTRAINT FK_MEDIOCONTACTOPRESTADOR_DELETEDBY FOREIGN KEY (DeletedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);


ALTER TABLE [dbo].[DomicilioPrestador]
ADD
    CONSTRAINT FK_DOMICILIOPRESTADOR_PRESTADOR FOREIGN KEY (IdPrestador) REFERENCES [dbo].[SER_Profesiona]([Id]),
    CONSTRAINT FK_DOMICILIOPRESTADOR_CREATEDBY FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]),
    CONSTRAINT FK_DOMICILIOPRESTADOR_DELETEDBY FOREIGN KEY (DeletedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);

ALTER TABLE [dbo].[PrestadorFHIR]
ADD
    CONSTRAINT FK_PRESTADOREFHIR_PRESTADOR FOREIGN KEY (IdPrestador) REFERENCES [dbo].[SER_Profesiona]([Id]),
    CONSTRAINT FK_PRESTADOREFHIR_GENEROADMINISTRATIVO FOREIGN KEY (FHIR_IdGeneroAdministrativo) REFERENCES [dbo].[TAB_DEIS_SexoBiologico]([Id]);

ALTER TABLE [dbo].[TituloProfesionalPrestador]
ADD
    CONSTRAINT FK_TITULOPROFESIONALPRESTADOR_PRESTADOR FOREIGN KEY (IdPrestador) REFERENCES [dbo].[SER_Profesiona]([Id]),
    CONSTRAINT FK_TITULOPROFESIONALPRESTADOR_TITULOPROFESIONAL FOREIGN KEY (IdTituloProfesional) REFERENCES [dbo].[TAB_DEIS_TituloProfesional]([Id]),
    CONSTRAINT FK_TITULOPROFESIONALPRESTADOR_CREATEDBY FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]),
    CONSTRAINT FK_TITULOPROFESIONALPRESTADOR_DELETEDBY FOREIGN KEY (DeletedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);
