/* 20 */
CREATE TABLE [dbo].[IdentificadorPaciente]
(
  Id UNIQUEIDENTIFIER DEFAULT NEWID() CONSTRAINT PK_IDENTIFICADORPACIENTE PRIMARY KEY,
  
  NumeroPaciente FLOAT NOT NULL,

  IdTipo TINYINT NOT NULL,
  IdUso TINYINT NULL,

  Valor VARCHAR(64) NOT NULL,

  IdPaisEmisorDocumento SMALLINT NOT NULL,

  [CreatedBy] [VARCHAR](10) NOT NULL DEFAULT SUSER_NAME(),
  [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),

  CONSTRAINT UQ_IDENTIFICADORPACIENTE_IDTIPO_VALOR UNIQUE (IdTipo, Valor)
);


ALTER TABLE [dbo].[IdentificadorPaciente] ADD
CONSTRAINT FK_IDENTIFICADORPACIENTE_PACIENTE FOREIGN KEY (NumeroPaciente) REFERENCES [dbo].[PAC_Paciente](PAC_PAC_Numero),
CONSTRAINT FK_IDENTIFICADORPACIENTE_TIPO FOREIGN KEY (IdTipo) REFERENCES [dbo].[TAB_FHIR_TipoIdentificadorPersona](Id),
CONSTRAINT FK_IDENTIFICADORPACIENTE_USO FOREIGN KEY (IdUso) REFERENCES [dbo].[TAB_FHIR_UsoIdentificadorPersona](Id),
CONSTRAINT FK_IDENTIFICADORPACIENTE_PAIS FOREIGN KEY (IdPaisEmisorDocumento) REFERENCES [dbo].[TAB_DEIS_Pais](Id),
CONSTRAINT FK_IDENTIFICADORPACIENTE_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);
