

CREATE TABLE [dbo].[IdentificadorPaciente]
(
  Id UNIQUEIDENTIFIER DEFAULT NEWID() CONSTRAINT PK_IDENTIFICADORPACIENTE PRIMARY KEY,
  
  NumeroPaciente FLOAT NOT NULL,

  IdTipo TINYINT NOT NULL,
  IdUso TINYINT NULL,

  Valor VARCHAR(64) NOT NULL,

  IdPaisEmisorDocumento SMALLINT NOT NULL,

  [CreatedBy] [VARCHAR](10) NOT NULL,
  [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),

  CONSTRAINT UQ_IDENTIFICADORPACIENTE_IDTIPO_VALOR UNIQUE (IdTipo, Valor)
);