/* 20 */
CREATE TABLE [dbo].[MedioContactoPaciente]
(
  Id UNIQUEIDENTIFIER DEFAULT NEWID() CONSTRAINT PK_MEDIOCONTACTOPACIENTE PRIMARY KEY,

  NumeroPaciente FLOAT NOT NULL,
  
  IdTipo TINYINT NOT NULL,
  CodigoUso VARCHAR(10) NOT NULL,
  
  Valor VARCHAR(100) NOT NULL,
  
  OrdenPreferencia INT NOT NULL,

  [CreatedBy] [VARCHAR](10) NOT NULL,
  [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),

  [DeletedBy] [VARCHAR](10) NULL,
  [DeletedAt] DATETIME NULL
);

ALTER TABLE [dbo].[MedioContactoPaciente] ADD
CONSTRAINT FK_MEDIOCONTACTO_PACIENTE FOREIGN KEY (NumeroPaciente) REFERENCES [dbo].[PAC_Paciente](PAC_PAC_Numero),
CONSTRAINT FK_MEDIOCONTACTO_TIPO FOREIGN KEY (IdTipo) REFERENCES [dbo].[TAB_TipoMedioContacto](Id),
CONSTRAINT FK_MEDIOCONTACTO_USO FOREIGN KEY (CodigoUso) REFERENCES [dbo].[TAB_FHIR_UsoMedioContacto](Codigo),
CONSTRAINT FK_MEDIOCONTACTO_CREATEDBY FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]),
CONSTRAINT FK_MEDIOCONTACTO_DELETEDBY FOREIGN KEY (DeletedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);
