

CREATE TABLE [dbo].[MedioContactoPaciente]
(
  Id UNIQUEIDENTIFIER DEFAULT NEWID() CONSTRAINT PK_MEDIOCONTACTOPACIENTE PRIMARY KEY,

  NumeroPaciente FLOAT NOT NULL,
  
  IdTipo TINYINT NOT NULL,
  CodigoUso VARCHAR(10) NOT NULL,
  
  Valor VARCHAR(100) NOT NULL,
  
  OrdenPreferencia INT NOT NULL,

  [CreatedBy] [VARCHAR](10) NOT NULL,
  [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),

  [DeletedBy] [VARCHAR](10) NULL,
  [DeletedAt] DATETIME NULL
);