/* 10 */
IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_SEXOBILOGICO', 'F') IS NULL)
    ALTER TABLE [dbo].[PAC_Paciente] ADD 
    CONSTRAINT FK_PAC_PACIENTE_SEXOBILOGICO FOREIGN KEY (IdSexoBiologico) REFERENCES [dbo].[TAB_DEIS_SexoBiologico]([Id])

IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_IDENTIDADGENERO', 'F') IS NULL)
    ALTER TABLE [dbo].[PAC_Paciente] ADD 
    CONSTRAINT FK_PAC_PACIENTE_IDENTIDADGENERO FOREIGN KEY (IdIdentidadGenero) REFERENCES [dbo].[TAB_DEIS_IdentidadGenero]([Id])

IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_NACIONALIDAD', 'F') IS NULL)
    ALTER TABLE [dbo].[PAC_Paciente] ADD 
    CONSTRAINT FK_PAC_PACIENTE_NACIONALIDAD FOREIGN KEY (IdNacionalidad) REFERENCES [dbo].[TAB_DEIS_Pais]([Id])

IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_PAISORIGEN', 'F') IS NULL)
    ALTER TABLE [dbo].[PAC_Paciente] ADD 
    CONSTRAINT FK_PAC_PACIENTE_PAISORIGEN FOREIGN KEY (IdPaisOrigen) REFERENCES [dbo].[TAB_DEIS_Pais]([Id])

IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_ESTADOCIVIL', 'F') IS NULL)
    ALTER TABLE [dbo].[PAC_Paciente] ADD 
    CONSTRAINT FK_PAC_PACIENTE_ESTADOCIVIL FOREIGN KEY (IdEstadoCivil) REFERENCES [dbo].[TAB_DEIS_EstadoCivil]([Id])

IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_PUEBLOORIGINARIO', 'F') IS NULL)
    ALTER TABLE [dbo].[PAC_Paciente] ADD 
    CONSTRAINT FK_PAC_PACIENTE_PUEBLOORIGINARIO FOREIGN KEY (IdPuebloOriginario) REFERENCES [dbo].[TAB_DEIS_PuebloOriginario]([Id])

IF (OBJECT_ID('dbo.FK_PAC_PACIENTE_RELIGION', 'F') IS NULL)
    ALTER TABLE [dbo].[PAC_Paciente] ADD 
    CONSTRAINT FK_PAC_PACIENTE_RELIGION FOREIGN KEY (IdReligion) REFERENCES [dbo].[TAB_DEIS_Religion]([Id])
