/* 15 */
CREATE TABLE [dbo].[RelacionPersonaContactoPaciente]
(
  IdPersonaContacto UNIQUEIDENTIFIER NOT NULL,
  CodigoRelacion CHAR(1) NOT NULL,
  CONSTRAINT PK_RELACIONPERSONACONTACTOPACIENTE PRIMARY KEY (IdPersonaContacto, CodigoRelacion),
  
  [CreatedBy] [VARCHAR](10) NOT NULL,
  [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE()
);

ALTER TABLE [dbo].[RelacionPersonaContactoPaciente] ADD
CONSTRAINT FK_RELACIONPERSONACONTACTOPACIENTE FOREIGN KEY (IdPersonaContacto) REFERENCES PersonaContactoPaciente(Id),
CONSTRAINT FK_RELACIONPERSONACONTACTOPACIENTE_RELACION FOREIGN KEY (CodigoRelacion) REFERENCES TAB_FHIR_RelacionContactoPaciente(Codigo),
CONSTRAINT FK_RELACIONPERSONACONTACTOPACIENTE_USUARIO FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);
