/* 20 */
CREATE TABLE [dbo].[MedioContactoPrestador]
(
  Id UNIQUEIDENTIFIER DEFAULT NEWID() CONSTRAINT PK_MEDIOCONTACTOPRESTADOR PRIMARY KEY,

  IdPrestador UNIQUEIDENTIFIER NOT NULL,
  
  IdTipo TINYINT NOT NULL,
  CodigoUso VARCHAR(10) NOT NULL,
  
  Valor VARCHAR(100) NOT NULL,
  
  OrdenPreferencia INT NOT NULL,

  [CreatedBy] [VARCHAR](10) NOT NULL,
  [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),

  [DeletedBy] [VARCHAR](10) NULL,
  [DeletedAt] DATETIME NULL
);


ALTER TABLE [dbo].[MedioContactoPrestador] ADD
CONSTRAINT FK_MEDIOCONTACTOPRESTADOR_PRESTADOR FOREIGN KEY (IdPrestador) REFERENCES [dbo].[SER_Profesiona]([Id]),
CONSTRAINT FK_MEDIOCONTACTOPRESTADOR_TIPOMEDIOCONTACTO FOREIGN KEY (IdTipo) REFERENCES [dbo].[TAB_TipoMedioContacto]([Id]),
CONSTRAINT FK_MEDIOCONTACTOPRESTADOR_CREATEDBY FOREIGN KEY (CreatedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]),
CONSTRAINT FK_MEDIOCONTACTOPRESTADOR_DELETEDBY FOREIGN KEY (DeletedBy) REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]);
