
DROP TABLE IF EXISTS [dbo].[IdentificadorPaciente];

CREATE TABLE [dbo].[IdentificadorPaciente]
(
  Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  
  NumeroPaciente FLOAT NOT NULL CONSTRAINT FK_IDENTIFICADORPACIENTE_PACIENTE FOREIGN KEY REFERENCES [dbo].[PAC_Paciente](PAC_PAC_Numero),

  IdTipo TINYINT NOT NULL CONSTRAINT FK_IDENTIFICADORPACIENTE_TIPO FOREIGN KEY REFERENCES [dbo].[TAB_FHIR_TipoIdentificadorPersona](Id),
  IdUso TINYINT NULL CONSTRAINT FK_IDENTIFICADORPACIENTE_USO FOREIGN KEY REFERENCES [dbo].[TAB_FHIR_UsoIdentificadorPersona](Id),

  Valor VARCHAR(64) NOT NULL,

  IdPaisEmisorDocumento SMALLINT NOT NULL CONSTRAINT FK_IDENTIFICADORPACIENTE_PAIS FOREIGN KEY REFERENCES [dbo].[TAB_DEIS_Pais](Id),

  [CreatedBy] [VARCHAR](10) NOT NULL CONSTRAINT FK_IDENTIFICADORPACIENTE_USUARIO FOREIGN KEY REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]),
  [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE()
);