IF OBJECT_ID(N'dbo.LenguajePaciente', N'U') IS NULL BEGIN
  CREATE TABLE [dbo].[LenguajePaciente]
  (
    NumeroPaciente FLOAT NOT NULL CONSTRAINT FK_LENGUAJE_PACIENTE FOREIGN KEY REFERENCES [dbo].[PAC_Paciente](PAC_PAC_Numero),
    CodigoLenguaje CHAR(5) NOT NULL CONSTRAINT FK_LENGUAJE_CODIGO FOREIGN KEY REFERENCES [dbo].[TAB_FHIR_Lenguaje](Codigo)
    CONSTRAINT PK_LENGUAJE_PACIENTE PRIMARY KEY (NumeroPaciente, CodigoLenguaje),

    [CreatedBy] [VARCHAR](10) NOT NULL CONSTRAINT FK_LENGUAJE_USUARIO FOREIGN KEY REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]),
	  [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE()
  );
END