
IF OBJECT_ID(N'dbo.MedioContactoPaciente', N'U') IS NULL BEGIN  
  CREATE TABLE [dbo].[MedioContactoPaciente]
  (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),

    NumeroPaciente FLOAT NOT NULL CONSTRAINT FK_PACIENTE_MEDIOCONTACTO FOREIGN KEY (NumeroPaciente) REFERENCES [dbo].[PAC_Paciente](PAC_PAC_Numero),
    IdTipo TINYINT NOT NULL CONSTRAINT FK_MEDIOCONTACTO_TIPO FOREIGN KEY (IdTipo) REFERENCES [dbo].[TAB_TipoMedioContacto](Id),
    CodigoUso VARCHAR(10) NOT NULL CONSTRAINT FK_MEDIOCONTACTO_USO FOREIGN KEY (CodigoUso) REFERENCES [dbo].[TAB_UsoMedioContacto](Codigo),
    
    Valor VARCHAR(100) NOT NULL CHECK(LEN(TRIM(Valor)) > 3),
    
    OrdenPreferencia INT NOT NULL,

    VigenteDesde DATETIME NULL,
    VigenteHasta DATETIME NULL,
  );
END