
DROP TABLE IF EXISTS [dbo].[MedioContactoPaciente];

CREATE TABLE [dbo].[MedioContactoPaciente]
(
  Id UNIQUEIDENTIFIER CONSTRAINT PK_MEDIOCONTACTO PRIMARY KEY DEFAULT NEWID(),

  NumeroPaciente FLOAT NOT NULL CONSTRAINT FK_MEDIOCONTACTO_PACIENTE FOREIGN KEY (NumeroPaciente) REFERENCES [dbo].[PAC_Paciente](PAC_PAC_Numero),
  
  IdTipo TINYINT NOT NULL CONSTRAINT FK_MEDIOCONTACTO_TIPO FOREIGN KEY (IdTipo) REFERENCES [dbo].[TAB_TipoMedioContacto](Id),
  CodigoUso VARCHAR(10) NOT NULL CONSTRAINT FK_MEDIOCONTACTO_USO FOREIGN KEY (CodigoUso) REFERENCES [dbo].[TAB_FHIR_UsoMedioContacto](Codigo),
  
  Valor VARCHAR(100) NOT NULL,
  
  OrdenPreferencia INT NOT NULL,

  [CreatedBy] [VARCHAR](10) NOT NULL CONSTRAINT FK_MEDIOCONTACTO_CREATEDBY FOREIGN KEY REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]),
  [CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),

  [DeletedBy] [VARCHAR](10) NULL CONSTRAINT FK_MEDIOCONTACTO_DELETEDBY FOREIGN KEY REFERENCES [dbo].[Segu_Usuarios]([Segu_Usr_Cuenta]),
  [DeletedAt] DATETIME NULL
);