CREATE TABLE [dbo].[PrestadorFHIR](
    Id UNIQUEIDENTIFIER DEFAULT NEWID() CONSTRAINT PK_PRESTADORFHIR PRIMARY KEY,

    IdPrestador [UNIQUEIDENTIFIER] NOT NULL,

    FHIR_Id VARCHAR(64) NOT NULL UNIQUE,
    FHIR_IdGeneroAdministrativo [TINYINT] NULL,
)
