ALTER TABLE [dbo].[SER_Profesiona]
DROP CONSTRAINT [PK_SER_PROFESIONA]

ALTER TABLE [dbo].[SER_Profesiona]
ADD
    [IdIdentidadGenero] [TINYINT] NULL,
    [IdNacionalidad] [SMALLINT] NULL,
    [NumeroRPNI] [BIGINT] NULL,

    [FechaNacimiento] [DATETIME] NULL,
    [IdSexoBiologico] [TINYINT] NULL,

    Id UNIQUEIDENTIFIER DEFAULT NEWID(),
    
    CONSTRAINT UQ_SER_PROFESIONA UNIQUE ([SER_PRO_Rut] ASC, [SER_PRO_Tipo] ASC, [SER_PRO_Procedencia] ASC),
    CONSTRAINT PK_SER_PROFESIONA PRIMARY KEY (Id);