/* 200 */
IF OBJECT_ID('dbo.PRLE_ESPECIALIDADES', 'U') IS NULL BEGIN

    CREATE TABLE [dbo].[PRLE_ESPECIALIDADES] (
        [Id] [int] IDENTITY(1,1) NOT NULL,
        [DESCRIPCION_DEIS_ESPECIALIDAD] [VARCHAR](250) NOT NULL,
        [IdTipoEspecialidad] [int] NOT NULL,
        [vigencia] [bit] NOT NULL DEFAULT 1,

        [CodigoFHIR] [VARCHAR](10),
    );

    INSERT INTO [dbo].[PRLE_ESPECIALIDADES] (CodigoFHIR, IdTipoEspecialidad, DESCRIPCION_DEIS_ESPECIALIDAD) VALUES
    ('1', '1', 'ANATOMÍA PATOLÓGICA'),
    ('2', '1', 'ANESTESIOLOGÍA'),
    ('3', '1', 'CARDIOLOGÍA'),
    ('4', '1', 'CIRUGÍA GENERAL'),
    ('5', '1', 'CIRUGÍA DE CABEZA, CUELLO Y MAXILOFACIAL'),
    ('6', '1', 'CIRUGÍA CARDIOVASCULAR'),
    ('7', '1', 'CIRUGÍA DE TÓRAX'),
    ('8', '1', 'CIRUGÍA PLÁSTICA Y REPARADORA'),
    ('9', '1', 'CIRUGÍA PEDIÁTRICA'),
    ('10', '1', 'CIRUGÍA VASCULAR PERIFÉRICA'),
    ('11', '1', 'COLOPROCTOLOGÍA'),
    ('12', '1', 'DERMATOLOGÍA'),
    ('13', '1', 'DIABETOLOGÍA'),
    ('14', '1', 'ENDOCRINOLOGÍA ADULTO'),
    ('15', '1', 'ENDOCRINOLOGÍA PEDIÁTRICA'),
    ('16', '1', 'ENFERMEDADES RESPIRATORIAS DEL ADULTO (BRONCOPULMONAR)'),
    ('17', '1', 'ENFERMEDADES RESPIRATORIAS PEDIÁTRICAS (BRONCOPULMONAR PEDIATRICO)'),
    ('18', '1', 'GASTROENTEROLOGÍA ADULTO'),
    ('19', '1', 'GASTROENTEROLOGÍA PEDIÁTRICA'),
    ('20', '1', 'GENÉTICA CLÍNICA'),
    ('21', '1', 'GERIATRÍA'),
    ('22', '1', 'GINECOLOGÍA PEDIÁTRICA Y DE LA ADOLESCENCIA'),
    ('23', '1', 'HEMATOLOGÍA'),
    ('24', '1', 'IMAGENOLOGÍA'),
    ('25', '1', 'INFECTOLOGÍA'),
    ('26', '1', 'INMUNOLOGÍA'),
    ('27', '1', 'LABORATORIO CLÍNICO'),
    ('28', '1', 'MEDICINA FAMILIAR'),
    ('29', '1', 'MEDICINA FÍSICA Y REHABILITACIÓN (FISIATRIA ADULTO)'),
    ('30', '1', 'MEDICINA INTERNA'),
    ('31', '1', 'MEDICINA INTENSIVA ADULTO'),
    ('32', '1', 'MEDICINA INTENSIVA PEDIÁTRICA'),
    ('33', '1', 'MEDICINA LEGAL'),
    ('34', '1', 'MEDICINA MATERNO INFANTIL'),
    ('35', '1', 'MEDICINA NUCLEAR'),
    ('36', '1', 'MEDICINA DE URGENCIA'),
    ('37', '1', 'NEFROLOGÍA ADULTO'),
    ('38', '1', 'NEFROLOGÍA PEDIÁTRICO'),
    ('39', '1', 'NEONATOLOGÍA'),
    ('40', '1', 'NEUROCIRUGÍA'),
    ('41', '1', 'NEUROLOGÍA ADULTO'),
    ('42', '1', 'NEUROLOGÍA PEDIÁTRICA'),
    ('43', '1', 'OBSTETRICIA Y GINECOLOGÍA'),
    ('44', '1', 'OFTALMOLOGÍA'),
    ('45', '1', 'ONCOLOGÍA MÉDICA'),
    ('46', '1', 'OTORRINOLARINGOLOGÍA'),
    ('47', '1', 'PEDIATRÍA'),
    ('48', '1', 'PSIQUIATRÍA ADULTO'),
    ('49', '1', 'PSIQUIATRÍA PEDIÁTRICA Y DE LA ADOLESCENCIA'),
    ('50', '1', 'RADIOTERAPIA ONCOLÓGICA'),
    ('51', '1', 'REUMATOLOGÍA'),
    ('52', '1', 'SALUD PÚBLICA'),
    ('53', '1', 'TRAUMATOLOGÍA Y ORTOPEDIA'),
    ('54', '1', 'UROLOGÍA'),
    ('55', '1', 'CARDIOLOGÍA PEDIÁTRICA'),
    ('56', '1', 'CIRUGÍA DIGESTIVA'),
    ('57', '1', 'CIRUGÍA PLASTICA Y REPARADORA PEDIÁTRICA'),
    ('58', '1', 'GINECOLOGÍA'),
    ('59', '1', 'HEMATO-ONCOLOGÍA PEDIÁTRICA'),
    ('60', '1', 'INFECTOLOGÍA PEDIATRICA'),
    ('61', '1', 'MEDICINA FAMILIAR DEL NIÑO'),
    ('62', '1', 'MEDICINA FISICA Y REHABILITACIÓN PEDIÁTRICA (FISIATRIA PEDIATRICA)'),
    ('63', '1', 'NUTRIÓLOGO'),
    ('64', '1', 'NUTRIÓLOGO PEDIÁTRICO'),
    ('65', '1', 'REUMATOLOGÍA PEDIÁTRICA'),
    ('66', '1', 'OBSTETRICIA'),
    ('67', '1', 'TRAUMATOLOGÍA Y ORTOPEDIA PEDIÁTRICA'),
    ('68', '1', 'UROLOGÍA PEDIÁTRICA'),
    ('1', '2', 'Cirugía y Traumatología Buco Maxilofacial'),
    ('2', '2', 'Cirugía Bucal'),
    ('3', '2', 'Endodoncia'),
    ('4', '2', 'Imagenología Oral y Maxilofacial'),
    ('5', '2', 'Implantología Buco Maxilofacial'),
    ('6', '2', 'Odontología legal'),
    ('7', '2', 'Odontopediatría'),
    ('8', '2', 'Ortodoncia y Ortopedia Dento Máxilo Facial'),
    ('9', '2', 'Patología Oral'),
    ('10', '2', 'Periodoncia'),
    ('11', '2', 'Rehabilitación Oral'),
    ('12', '2', 'Salud Pública'),
    ('13', '2', 'Somato-Prótesis'),
    ('14', '2', 'Trastornos Temporomandibulares Y Dolor Orofacial');
END